# A set of configuration
defaults:
  - _self_
  - workload/training: unet3d  # Default training workload (can be overridden)
  - override hydra/job_logging: disabled  
  - override hydra/hydra_logging: disabled
hydra:
  run:
    dir: ./results/${workload.model}/${now:%Y-%m-%d}-${now:%H-%M-%S}
